
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


# Example configuration.yaml entry
sensor:
  - platform: mqtt
    unique_id: "moxy_1_current"
    name: "Moxy 1 Current"
    state_topic: "moxy/current/1"
    state_class: "measurement"
    device_class: "current"
    unit_of_measurement: "A"
  - platform: mqtt
    unique_id: "moxy_2_current"
    name: "Moxy 2 Current"
    state_topic: "moxy/current/2"
    state_class: "measurement"
    device_class: "current"
    unit_of_measurement: "A"
  - platform: mqtt
    unique_id: "moxy_3_current"
    name: "Moxy 3 Current"
    state_topic: "moxy/current/3"
    state_class: "measurement"
    device_class: "current"
    unit_of_measurement: "A"
  - platform: mqtt
    unique_id: "moxy_4_current"
    name: "Moxy 4 Current"
    state_topic: "moxy/current/4"
    state_class: "measurement"
    device_class: "current"
    unit_of_measurement: "A"
  - platform: mqtt
    unique_id: "moxy_rack_temp"
    name: "Moxy Rack Temp"
    state_topic: "moxy/temp"
    state_class: "measurement"
    device_class: "temperature"
    unit_of_measurement: "C"
  - platform: mqtt
    unique_id: "moxy_rack_humidity"
    name: "Moxy Rack Humidity"
    state_topic: "moxy/humidity"
    state_class: "measurement"
    device_class: "humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    unique_id: "moxy_rack_gas"
    name: "Moxy Rack Gas"
    state_topic: "moxy/gas"
    state_class: "measurement"
    device_class: "volatile_organic_compounds"
    unit_of_measurement: "µg/m³"
  # - platform: mqtt
  #   unique_id: "moxy_psu_voltage"
  #   name: "Moxy PSU Voltage"
  #   state_topic: "moxy/voltage/psu"
  #   state_class: "measurement"
  #   device_class: "voltage"
  #   unit_of_measurement: "V"

template:
  # - trigger:
  #     - platform: time_pattern
  #       # This will update every night
  #       hours: 0
  #       minutes: 0
  # - sensor:
  #     # Keep track how many days have past since a date
  #     - name: "Moxy 1 Power"
  #       unique_id: "moxy_1_power"
  #       state_class: "measurement"
  #       unit_of_measurement: "W"
  #       device_class: "power"
  #       state: "{{ 11.5 * states('sensor.moxy_1_current') | float | round(2) }}"

switch:
  - platform: mqtt
    unique_id: moxy_2_switch
    name: "Moxy 2 Power Switch"
    state_topic: "moxy/power/switch/2"
    command_topic: "moxy/power/switch/2/set"
    # availability:
    #   - topic: "moxy/power/switch/2/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    unique_id: moxy_1_switch
    name: "Moxy 1 Power Switch"
    state_topic: "moxy/power/switch/1"
    command_topic: "moxy/power/switch/1/set"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
